### ISSUE TITLE
I find  some crash issues 

### ISSUE THREAD

**Issue by YYYSSSHHH** [Sparker0i/Weather-Kotlin#15]
**Environment Info：**
APK download Download address：： https://f-droid.org/zh_Hans/packages/com.a5corp.weather/
APK  Version: 5.3.2 (656) 
AndroidOS Version = 6.0.1

**Description information：**
We find that mobile apps are prone to crashes due to a network issue, mainly because successful network API calls return unexpected or no data.
And we found that when this app's network returned data is null ，or the network request fails (status code is 404/503) the app has crashed.

**crash information：**

###  _Crash One:_
crashActivity=com.a5corp.weather.activity.WeatherActivity

 : 

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.a5corp.weather.model.WeatherFort.getCod()' on a null object reference
	at com.a5corp.weather.b.b.a(dalvik_source_simpleweather_656.apk)
	at com.a5corp.weather.b.b.doInBackground(dalvik_source_simpleweather_656.apk)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.a5corp.weather.model.WeatherFort.getCod()' on a null object reference
	at com.a5corp.weather.b.b.a(dalvik_source_simpleweather_656.apk)
	at com.a5corp.weather.b.b.doInBackground(dalvik_source_simpleweather_656.apk)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

### _Crash Two:_
crashActivity=com.a5corp.weather.activity.WeatherActivity

 :

java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
	at java.lang.String.startEndAndLength(String.java:298)
	at java.lang.String.substring(String.java:1087)
	at com.a5corp.weather.fragment.a.ae(dalvik_source_simpleweather_656.apk)
	at com.a5corp.weather.fragment.a.ad(dalvik_source_simpleweather_656.apk)
	at com.a5corp.weather.fragment.a.a(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.i.b(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.a(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.e(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.a(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.c.d(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.b(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.a(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.b(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o.f(dalvik_source_simpleweather_656.apk)
	at android.support.v4.a.o$1.run(dalvik_source_simpleweather_656.apk)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Finally：**
The cause of the program crash may be that the network response data is not handled properly in the code, such as null 
If you have confirmed or fixed this problem, please give me a reply, thank you!

**Comment by YYYSSSHHH** [comment]
How do we test the APP?
We use the fuzzing method to simulate the network response data. For example, when the app receives network API response data from server or network, we will replace it with 404, null and random data.
#A very simple example:
normal data ：Value=”hello” -----fuzzing-----> simulated data ：Value=null or network request fails（404、503） or Value=”heee”(random data) or Value=""(empty) , etc.
